SET SCHEMA APP;
CREATE TABLE USERS (
  NAME   VARCHAR(20) NOT NULL PRIMARY KEY,
  PASSWORD  VARCHAR(20) NOT NULL,
  STATUS  VARCHAR(20) NOT NULL,
  SURNAME  VARCHAR(20) NOT NULL
);
INSERT INTO USERS VALUES('alice', 'security', 'true', 'yellow');
INSERT INTO USERS VALUES('bob', 'security', 'true', 'blue');
CREATE TABLE ROLES (
  NAME   VARCHAR(20) NOT NULL PRIMARY KEY,
  ROLE   VARCHAR(20) NOT NULL
);
INSERT INTO ROLES VALUES('alice', 'boss');
